### ISSUE TITLE
Can't launch project

### ISSUE THREAD

**Issue by PeterBan11** [michaelkolesidis/3d-cube#1]
Hi there!
I'm trying to learn Three.JS
I have installed VS Code, node.js, vite and Three using npm.
But i can't understand, how to launch project.
When I run command in terminal: "node 3d-cube.js"
I get Error: "ReferenceError: THREE is not defined"

**Comment by michaelkolesidis** [comment]
Hello, this project is using p5.js, not Three.js. In order to run it, you just need to open and serve index.html file using the live server extension of VSCode.
